repos:
  - repo: local
    hooks:
      # Backend: Linting + Typecheck
      - id: lint
        name: lint
        entry: mise lint
        language: system
        pass_filenames: false
        # files: ^backend/

      # Backend: Formatting
      - id: format
        name: format
        entry: mise format
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^frontend/tsconfig\.tsbuildinfo$
      - id: end-of-file-fixer
        exclude: ^frontend/tsconfig\.tsbuildinfo$
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
