version: "2"

linters:
  enable:
    - revive
    - govet
    - errcheck
    - gosec
    - staticcheck
    - unused
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - scraper
